# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xmanager/xm_local/storage/data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$xmanager/xm_local/storage/data.proto\x12\x08xmanager\"\xd1\x01\n\x03Job\x12#\n\x05local\x18\x01 \x01(\x0b\x32\x12.xmanager.LocalJobH\x00\x12\'\n\x04\x63\x61ip\x18\x02 \x01(\x0b\x32\x17.xmanager.AIPlatformJobH\x00\x12-\n\nkubernetes\x18\x03 \x01(\x0b\x32\x17.xmanager.KubernetesJobH\x00\x12\x45\n\x17vertex_training_cluster\x18\x04 \x01(\x0b\x32\".xmanager.VertexTrainingClusterJobH\x00\x42\x06\n\x04kind\"7\n\x08LocalJob\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12\x0b\n\x03\x63md\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"&\n\rAIPlatformJob\x12\x15\n\rresource_name\x18\x01 \x01(\t\"4\n\rKubernetesJob\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x10\n\x08job_name\x18\x02 \x01(\t\"\xad\x01\n\x18VertexTrainingClusterJob\x12\x14\n\x0cslurm_job_id\x18\x01 \x01(\t\x12\x12\n\nlogin_node\x18\x02 \x01(\t\x12\x14\n\x0c\x63luster_type\x18\x03 \x01(\t\x12\x11\n\tpartition\x18\x04 \x01(\t\x12\x16\n\x0euse_gcloud_ssh\x18\x05 \x01(\x08\x12\x14\n\x0cssh_hostname\x18\x06 \x01(\t\x12\x10\n\x08work_dir\x18\x07 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xmanager.xm_local.storage.data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOB._serialized_start=51
  _JOB._serialized_end=260
  _LOCALJOB._serialized_start=262
  _LOCALJOB._serialized_end=317
  _AIPLATFORMJOB._serialized_start=319
  _AIPLATFORMJOB._serialized_end=357
  _KUBERNETESJOB._serialized_start=359
  _KUBERNETESJOB._serialized_end=411
  _VERTEXTRAININGCLUSTERJOB._serialized_start=414
  _VERTEXTRAININGCLUSTERJOB._serialized_end=587
# @@protoc_insertion_point(module_scope)
